version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: focus-breaker
    main: ./main.go
    binary: focus-breaker

    env:
      - CGO_ENABLED=1

    goos:
      - windows
      - linux

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
          - CGO_ENABLED=1

      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
          - CGO_ENABLED=1

archives:
  - id: default
    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        formats:
          - zip

    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "README"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: borgmon
    name: focus-breaker

  draft: false
  prerelease: auto
  mode: replace

  name_template: "v{{.Version}}"

  header: |
    ## Release {{.Tag}}

  footer: |
    **Full Changelog**: https://github.com/borgmon/focus-breaker/compare/{{.PreviousTag}}...{{.Tag}}
