version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: focus-breaker
    main: ./main.go
    binary: focus-breaker

    env:
      - CGO_ENABLED=1

    goos:
      - windows
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    # Ensure only the targets we want
    targets:
      - windows_amd64_v1
      - linux_amd64_v1
      - linux_arm64
      - darwin_arm64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "README"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: borgmon
    name: focus-breaker

  draft: false
  prerelease: auto
  mode: replace

  name_template: "v{{.Version}}"

  header: |
    ## Release {{.Tag}}

  footer: |
    **Full Changelog**: https://github.com/borgmon/focus-breaker/compare/{{.PreviousTag}}...{{.Tag}}
