// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/alarm.wav
var resourceAlarmWavData []byte
var resourceAlarmWav = &fyne.StaticResource{
	StaticName:    "assets/alarm.wav",
	StaticContent: resourceAlarmWavData,
}

//go:embed assets/icon-transparent.png
var resourceIconTransparentPngData []byte
var resourceIconTransparentPng = &fyne.StaticResource{
	StaticName:    "assets/icon-transparent.png",
	StaticContent: resourceIconTransparentPngData,
}

//go:embed assets/Icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "assets/Icon.png",
	StaticContent: resourceIconPngData,
}
